2017-05-12 18:43:16 WARN [com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#4] [com.mchange.v2.c3p0.impl.DefaultConnectionTester:?] - SQL State '08001' of Exception which occurred during a Connection test (fallback DatabaseMetaData test) implies that the database is invalid, and the pool should refill itself with fresh Connections.
com.ibm.db2.jcc.am.DisconnectNonTransientConnectionException: [jcc][t4][2030][11211][4.11.77] 在对连接的底层 socket、socket input stream 或 socket output stream 执行操作期间
发生通信错误。错误位置：Reply.fill() - socketInputStream.read (-1)。消息：Connection reset。 ERRORCODE=-4499, SQLSTATE=08001
	at com.ibm.db2.jcc.am.gd.a(gd.java:319)
	at com.ibm.db2.jcc.t4.a.a(a.java:461)
	at com.ibm.db2.jcc.t4.a.a(a.java:456)
	at com.ibm.db2.jcc.t4.z.b(z.java:206)
	at com.ibm.db2.jcc.t4.z.c(z.java:259)
	at com.ibm.db2.jcc.t4.z.c(z.java:372)
	at com.ibm.db2.jcc.t4.z.v(z.java:1147)
	at com.ibm.db2.jcc.t4.cb.f(cb.java:103)
	at com.ibm.db2.jcc.t4.q.f(q.java:87)
	at com.ibm.db2.jcc.t4.b.a(b.java:3642)
	at com.ibm.db2.jcc.am.cg.b(cg.java:41)
	at com.ibm.db2.jcc.am.hg.b(hg.java:196)
	at com.ibm.db2.jcc.am.o.j(o.java:579)
	at com.ibm.db2.jcc.am.o.g(o.java:325)
	at com.ibm.db2.jcc.t4.a.g(a.java:626)
	at com.ibm.db2.jcc.am.o.a(o.java:206)
	at com.ibm.db2.jcc.am.kn.b(kn.java:3799)
	at com.ibm.db2.jcc.am.ln.fc(ln.java:152)
	at com.ibm.db2.jcc.am.lc.a(lc.java:7809)
	at com.ibm.db2.jcc.am.lc.a(lc.java:6315)
	at com.ibm.db2.jcc.am.lc.getTables(lc.java:6221)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:185)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:62)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:67)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:368)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:310)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:1999)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:547)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:196)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at com.ibm.db2.jcc.t4.z.b(z.java:199)
	... 24 more
2017-05-12 18:43:16 WARN [Thread-11] [com.mchange.v2.c3p0.impl.DefaultConnectionTester:?] - SQL State '08001' of Exception tested by statusOnException() implies that the database is invalid, and the pool should refill itself with fresh Connections.
com.ibm.db2.jcc.am.DisconnectNonTransientConnectionException: [jcc][t4][2030][11211][4.11.77] 在对连接的底层 socket、socket input stream 或 socket output stream 执行操作期间
发生通信错误。错误位置：T4Agent.sendRequest() - flush (-1)。消息：Broken pipe。 ERRORCODE=-4499, SQLSTATE=08001
	at com.ibm.db2.jcc.am.gd.a(gd.java:319)
	at com.ibm.db2.jcc.t4.a.a(a.java:461)
	at com.ibm.db2.jcc.t4.a.a(a.java:456)
	at com.ibm.db2.jcc.t4.a.C(a.java:397)
	at com.ibm.db2.jcc.t4.a.r(a.java:354)
	at com.ibm.db2.jcc.am.o.a(o.java:204)
	at com.ibm.db2.jcc.am.kn.b(kn.java:3799)
	at com.ibm.db2.jcc.am.kn.ic(kn.java:2269)
	at com.ibm.db2.jcc.am.kn.execute(kn.java:2249)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.execute(NewProxyPreparedStatement.java:989)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:59)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:73)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:60)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:267)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:137)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:120)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:108)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:102)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:358)
	at com.sun.proxy.$Proxy21.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:191)
	at com.yeepay.g3.utils.persistence.mybatis.GenericDaoDefault.query(GenericDaoDefault.java:97)
	at com.yeepay.g3.utils.config.dao.impl.ConfigVersionDaoImpl.queryAll(ConfigVersionDaoImpl.java:45)
	at com.yeepay.g3.utils.config.service.impl.ConfigServiceImpl.queryConfigVersion(ConfigServiceImpl.java:285)
	at com.yeepay.g3.utils.config.biz.ConfigQueryBiz.queryConfigVersion(ConfigQueryBiz.java:66)
	at com.yeepay.g3.utils.config.impl.DefaultConfigRepository.refreshConfig(DefaultConfigRepository.java:157)
	at com.yeepay.g3.utils.config.impl.DefaultConfigRepository.refresh(DefaultConfigRepository.java:302)
	at com.yeepay.g3.utils.config.ConfigRepositoryFacatory$2.run(ConfigRepositoryFacatory.java:117)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
	at com.ibm.db2.jcc.t4.fb.b(fb.java:1685)
	at com.ibm.db2.jcc.t4.fb.a(fb.java:1633)
	at com.ibm.db2.jcc.t4.a.C(a.java:390)
	... 30 more
2017-05-12 18:43:16 WARN [com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#2] [com.mchange.v2.c3p0.impl.DefaultConnectionTester:?] - SQL State '08001' of Exception which occurred during a Connection test (fallback DatabaseMetaData test) implies that the database is invalid, and the pool should refill itself with fresh Connections.
com.ibm.db2.jcc.am.DisconnectNonTransientConnectionException: [jcc][t4][2030][11211][4.11.77] 在对连接的底层 socket、socket input stream 或 socket output stream 执行操作期间
发生通信错误。错误位置：Reply.fill() - socketInputStream.read (-1)。消息：Connection reset。 ERRORCODE=-4499, SQLSTATE=08001
	at com.ibm.db2.jcc.am.gd.a(gd.java:319)
	at com.ibm.db2.jcc.t4.a.a(a.java:461)
	at com.ibm.db2.jcc.t4.a.a(a.java:456)
	at com.ibm.db2.jcc.t4.z.b(z.java:206)
	at com.ibm.db2.jcc.t4.z.c(z.java:259)
	at com.ibm.db2.jcc.t4.z.c(z.java:372)
	at com.ibm.db2.jcc.t4.z.v(z.java:1147)
	at com.ibm.db2.jcc.t4.cb.f(cb.java:103)
	at com.ibm.db2.jcc.t4.q.f(q.java:87)
	at com.ibm.db2.jcc.t4.b.a(b.java:3642)
	at com.ibm.db2.jcc.am.cg.b(cg.java:41)
	at com.ibm.db2.jcc.am.hg.b(hg.java:196)
	at com.ibm.db2.jcc.am.o.j(o.java:579)
	at com.ibm.db2.jcc.am.o.g(o.java:325)
	at com.ibm.db2.jcc.t4.a.g(a.java:626)
	at com.ibm.db2.jcc.am.o.a(o.java:206)
	at com.ibm.db2.jcc.am.kn.b(kn.java:3799)
	at com.ibm.db2.jcc.am.ln.fc(ln.java:152)
	at com.ibm.db2.jcc.am.lc.a(lc.java:7809)
	at com.ibm.db2.jcc.am.lc.a(lc.java:6315)
	at com.ibm.db2.jcc.am.lc.getTables(lc.java:6221)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:185)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:62)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:67)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:368)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:310)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:1999)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:547)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:196)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at com.ibm.db2.jcc.t4.z.b(z.java:199)
	... 24 more
2017-05-12 18:43:16 WARN [Thread-17] [com.mchange.v2.c3p0.impl.DefaultConnectionTester:?] - SQL State '08001' of Exception tested by statusOnException() implies that the database is invalid, and the pool should refill itself with fresh Connections.
com.ibm.db2.jcc.am.DisconnectNonTransientConnectionException: [jcc][t4][2030][11211][4.11.77] 在对连接的底层 socket、socket input stream 或 socket output stream 执行操作期间
发生通信错误。错误位置：T4Agent.sendRequest() - flush (-1)。消息：Broken pipe。 ERRORCODE=-4499, SQLSTATE=08001
	at com.ibm.db2.jcc.am.gd.a(gd.java:319)
	at com.ibm.db2.jcc.t4.a.a(a.java:461)
	at com.ibm.db2.jcc.t4.a.a(a.java:456)
	at com.ibm.db2.jcc.t4.a.C(a.java:397)
	at com.ibm.db2.jcc.t4.a.r(a.java:354)
	at com.ibm.db2.jcc.am.o.a(o.java:204)
	at com.ibm.db2.jcc.am.jn.a(jn.java:3007)
	at com.ibm.db2.jcc.am.jn.a(jn.java:674)
	at com.ibm.db2.jcc.am.jn.executeQuery(jn.java:658)
	at com.mchange.v2.c3p0.impl.NewProxyStatement.executeQuery(NewProxyStatement.java:35)
	at com.yeepay.utils.jdbc.dal.support.separate.DsStatusDetector.doDetect(DsStatusDetector.java:104)
	at com.yeepay.utils.jdbc.dal.support.separate.DsStatusDetector$1.run(DsStatusDetector.java:80)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
	at com.ibm.db2.jcc.t4.fb.b(fb.java:1685)
	at com.ibm.db2.jcc.t4.fb.a(fb.java:1633)
	at com.ibm.db2.jcc.t4.a.C(a.java:390)
	... 9 more
2017-05-12 18:43:16 WARN [com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#3] [com.mchange.v2.c3p0.impl.DefaultConnectionTester:?] - SQL State '08001' of Exception which occurred during a Connection test (fallback DatabaseMetaData test) implies that the database is invalid, and the pool should refill itself with fresh Connections.
com.ibm.db2.jcc.am.DisconnectNonTransientConnectionException: [jcc][t4][2030][11211][4.11.77] 在对连接的底层 socket、socket input stream 或 socket output stream 执行操作期间
发生通信错误。错误位置：Reply.fill() - socketInputStream.read (-1)。消息：Connection reset。 ERRORCODE=-4499, SQLSTATE=08001
	at com.ibm.db2.jcc.am.gd.a(gd.java:319)
	at com.ibm.db2.jcc.t4.a.a(a.java:461)
	at com.ibm.db2.jcc.t4.a.a(a.java:456)
	at com.ibm.db2.jcc.t4.z.b(z.java:206)
	at com.ibm.db2.jcc.t4.z.c(z.java:259)
	at com.ibm.db2.jcc.t4.z.c(z.java:372)
	at com.ibm.db2.jcc.t4.z.v(z.java:1147)
	at com.ibm.db2.jcc.t4.cb.e(cb.java:96)
	at com.ibm.db2.jcc.t4.q.e(q.java:81)
	at com.ibm.db2.jcc.t4.rb.k(rb.java:160)
	at com.ibm.db2.jcc.am.jn.lb(jn.java:2179)
	at com.ibm.db2.jcc.am.kn.b(kn.java:3920)
	at com.ibm.db2.jcc.am.ln.fc(ln.java:152)
	at com.ibm.db2.jcc.am.lc.a(lc.java:7809)
	at com.ibm.db2.jcc.am.lc.a(lc.java:6315)
	at com.ibm.db2.jcc.am.lc.getTables(lc.java:6221)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:185)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:62)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:67)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:368)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:310)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:1999)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:547)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:196)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at com.ibm.db2.jcc.t4.z.b(z.java:199)
	... 19 more
2017-05-12 18:43:16 WARN [com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#2] [com.mchange.v2.c3p0.impl.DefaultConnectionTester:?] - SQL State '08001' of Exception which occurred during a Connection test (fallback DatabaseMetaData test) implies that the database is invalid, and the pool should refill itself with fresh Connections.
com.ibm.db2.jcc.am.DisconnectNonTransientConnectionException: [jcc][t4][2030][11211][4.11.77] 在对连接的底层 socket、socket input stream 或 socket output stream 执行操作期间
发生通信错误。错误位置：Reply.fill() - socketInputStream.read (-1)。消息：Connection reset。 ERRORCODE=-4499, SQLSTATE=08001
	at com.ibm.db2.jcc.am.gd.a(gd.java:319)
	at com.ibm.db2.jcc.t4.a.a(a.java:461)
	at com.ibm.db2.jcc.t4.a.a(a.java:456)
	at com.ibm.db2.jcc.t4.z.b(z.java:206)
	at com.ibm.db2.jcc.t4.z.c(z.java:259)
	at com.ibm.db2.jcc.t4.z.c(z.java:372)
	at com.ibm.db2.jcc.t4.z.v(z.java:1147)
	at com.ibm.db2.jcc.t4.cb.f(cb.java:103)
	at com.ibm.db2.jcc.t4.q.f(q.java:87)
	at com.ibm.db2.jcc.t4.b.a(b.java:3642)
	at com.ibm.db2.jcc.am.cg.b(cg.java:41)
	at com.ibm.db2.jcc.am.hg.b(hg.java:196)
	at com.ibm.db2.jcc.am.o.j(o.java:579)
	at com.ibm.db2.jcc.am.o.g(o.java:325)
	at com.ibm.db2.jcc.t4.a.g(a.java:626)
	at com.ibm.db2.jcc.am.o.a(o.java:206)
	at com.ibm.db2.jcc.am.kn.b(kn.java:3799)
	at com.ibm.db2.jcc.am.ln.fc(ln.java:152)
	at com.ibm.db2.jcc.am.lc.a(lc.java:7809)
	at com.ibm.db2.jcc.am.lc.a(lc.java:6315)
	at com.ibm.db2.jcc.am.lc.getTables(lc.java:6221)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:185)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:62)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:67)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:368)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:310)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:1999)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:547)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:196)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at com.ibm.db2.jcc.t4.z.b(z.java:199)
	... 24 more
2017-05-12 18:43:16 WARN [com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#4] [com.mchange.v2.c3p0.impl.DefaultConnectionTester:?] - SQL State '08001' of Exception which occurred during a Connection test (fallback DatabaseMetaData test) implies that the database is invalid, and the pool should refill itself with fresh Connections.
com.ibm.db2.jcc.am.DisconnectNonTransientConnectionException: [jcc][t4][2030][11211][4.11.77] 在对连接的底层 socket、socket input stream 或 socket output stream 执行操作期间
发生通信错误。错误位置：T4Agent.sendRequest() - flush (-1)。消息：Broken pipe。 ERRORCODE=-4499, SQLSTATE=08001
	at com.ibm.db2.jcc.am.gd.a(gd.java:319)
	at com.ibm.db2.jcc.t4.a.a(a.java:461)
	at com.ibm.db2.jcc.t4.a.a(a.java:456)
	at com.ibm.db2.jcc.t4.a.C(a.java:397)
	at com.ibm.db2.jcc.t4.a.r(a.java:354)
	at com.ibm.db2.jcc.am.o.a(o.java:204)
	at com.ibm.db2.jcc.am.kn.b(kn.java:3799)
	at com.ibm.db2.jcc.am.ln.fc(ln.java:152)
	at com.ibm.db2.jcc.am.lc.a(lc.java:7809)
	at com.ibm.db2.jcc.am.lc.a(lc.java:6315)
	at com.ibm.db2.jcc.am.lc.getTables(lc.java:6221)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:185)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:62)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:67)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:368)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:310)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:1999)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:547)
Caused by: java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
	at com.ibm.db2.jcc.t4.fb.b(fb.java:1685)
	at com.ibm.db2.jcc.t4.fb.a(fb.java:1633)
	at com.ibm.db2.jcc.t4.a.C(a.java:390)
	... 14 more
2017-05-12 18:43:16 WARN [com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#4] [com.mchange.v2.c3p0.impl.DefaultConnectionTester:?] - SQL State '08001' of Exception which occurred during a Connection test (fallback DatabaseMetaData test) implies that the database is invalid, and the pool should refill itself with fresh Connections.
com.ibm.db2.jcc.am.DisconnectNonTransientConnectionException: [jcc][t4][2030][11211][4.11.77] 在对连接的底层 socket、socket input stream 或 socket output stream 执行操作期间
发生通信错误。错误位置：T4Agent.sendRequest() - flush (-1)。消息：Broken pipe。 ERRORCODE=-4499, SQLSTATE=08001
	at com.ibm.db2.jcc.am.gd.a(gd.java:319)
	at com.ibm.db2.jcc.t4.a.a(a.java:461)
	at com.ibm.db2.jcc.t4.a.a(a.java:456)
	at com.ibm.db2.jcc.t4.a.C(a.java:397)
	at com.ibm.db2.jcc.t4.a.r(a.java:354)
	at com.ibm.db2.jcc.am.o.a(o.java:204)
	at com.ibm.db2.jcc.am.kn.b(kn.java:3799)
	at com.ibm.db2.jcc.am.ln.fc(ln.java:152)
	at com.ibm.db2.jcc.am.lc.a(lc.java:7809)
	at com.ibm.db2.jcc.am.lc.a(lc.java:6315)
	at com.ibm.db2.jcc.am.lc.getTables(lc.java:6221)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:185)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:62)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:67)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:368)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:310)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:1999)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:547)
Caused by: java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
	at com.ibm.db2.jcc.t4.fb.b(fb.java:1685)
	at com.ibm.db2.jcc.t4.fb.a(fb.java:1633)
	at com.ibm.db2.jcc.t4.a.C(a.java:390)
	... 14 more
2017-05-12 18:43:16 WARN [com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#0] [com.mchange.v2.c3p0.impl.DefaultConnectionTester:?] - SQL State '08001' of Exception which occurred during a Connection test (fallback DatabaseMetaData test) implies that the database is invalid, and the pool should refill itself with fresh Connections.
com.ibm.db2.jcc.am.DisconnectNonTransientConnectionException: [jcc][t4][2030][11211][4.11.77] 在对连接的底层 socket、socket input stream 或 socket output stream 执行操作期间
发生通信错误。错误位置：Reply.fill() - socketInputStream.read (-1)。消息：Connection reset。 ERRORCODE=-4499, SQLSTATE=08001
	at com.ibm.db2.jcc.am.gd.a(gd.java:319)
	at com.ibm.db2.jcc.t4.a.a(a.java:461)
	at com.ibm.db2.jcc.t4.a.a(a.java:456)
	at com.ibm.db2.jcc.t4.z.b(z.java:206)
	at com.ibm.db2.jcc.t4.z.c(z.java:259)
	at com.ibm.db2.jcc.t4.z.c(z.java:372)
	at com.ibm.db2.jcc.t4.z.v(z.java:1147)
	at com.ibm.db2.jcc.t4.cb.f(cb.java:103)
	at com.ibm.db2.jcc.t4.q.f(q.java:87)
	at com.ibm.db2.jcc.t4.b.a(b.java:3642)
	at com.ibm.db2.jcc.am.cg.b(cg.java:41)
	at com.ibm.db2.jcc.am.hg.b(hg.java:196)
	at com.ibm.db2.jcc.am.o.j(o.java:579)
	at com.ibm.db2.jcc.am.o.g(o.java:325)
	at com.ibm.db2.jcc.t4.a.g(a.java:626)
	at com.ibm.db2.jcc.am.o.a(o.java:206)
	at com.ibm.db2.jcc.am.kn.b(kn.java:3799)
	at com.ibm.db2.jcc.am.ln.fc(ln.java:152)
	at com.ibm.db2.jcc.am.lc.a(lc.java:7809)
	at com.ibm.db2.jcc.am.lc.a(lc.java:6315)
	at com.ibm.db2.jcc.am.lc.getTables(lc.java:6221)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:185)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:62)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:67)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:368)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:310)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:1999)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:547)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:196)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at com.ibm.db2.jcc.t4.z.b(z.java:199)
	... 24 more
2017-05-12 18:43:16 WARN [com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#0] [com.mchange.v2.c3p0.impl.DefaultConnectionTester:?] - SQL State '08001' of Exception which occurred during a Connection test (fallback DatabaseMetaData test) implies that the database is invalid, and the pool should refill itself with fresh Connections.
com.ibm.db2.jcc.am.DisconnectNonTransientConnectionException: [jcc][t4][2030][11211][4.11.77] 在对连接的底层 socket、socket input stream 或 socket output stream 执行操作期间
发生通信错误。错误位置：Reply.fill() - socketInputStream.read (-1)。消息：Connection reset。 ERRORCODE=-4499, SQLSTATE=08001
	at com.ibm.db2.jcc.am.gd.a(gd.java:319)
	at com.ibm.db2.jcc.t4.a.a(a.java:461)
	at com.ibm.db2.jcc.t4.a.a(a.java:456)
	at com.ibm.db2.jcc.t4.z.b(z.java:206)
	at com.ibm.db2.jcc.t4.z.c(z.java:259)
	at com.ibm.db2.jcc.t4.z.c(z.java:372)
	at com.ibm.db2.jcc.t4.z.v(z.java:1147)
	at com.ibm.db2.jcc.t4.cb.f(cb.java:103)
	at com.ibm.db2.jcc.t4.q.f(q.java:87)
	at com.ibm.db2.jcc.t4.b.a(b.java:3642)
	at com.ibm.db2.jcc.am.cg.b(cg.java:41)
	at com.ibm.db2.jcc.am.hg.b(hg.java:196)
	at com.ibm.db2.jcc.am.o.j(o.java:579)
	at com.ibm.db2.jcc.am.o.g(o.java:325)
	at com.ibm.db2.jcc.t4.a.g(a.java:626)
	at com.ibm.db2.jcc.am.o.a(o.java:206)
	at com.ibm.db2.jcc.am.kn.b(kn.java:3799)
	at com.ibm.db2.jcc.am.ln.fc(ln.java:152)
	at com.ibm.db2.jcc.am.lc.a(lc.java:7809)
	at com.ibm.db2.jcc.am.lc.a(lc.java:6315)
	at com.ibm.db2.jcc.am.lc.getTables(lc.java:6221)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:185)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:62)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:67)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:368)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:310)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:1999)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:547)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:196)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at com.ibm.db2.jcc.t4.z.b(z.java:199)
	... 24 more
2017-05-12 18:43:16 WARN [com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#4] [com.mchange.v2.c3p0.impl.DefaultConnectionTester:?] - SQL State '08001' of Exception which occurred during a Connection test (fallback DatabaseMetaData test) implies that the database is invalid, and the pool should refill itself with fresh Connections.
com.ibm.db2.jcc.am.DisconnectNonTransientConnectionException: [jcc][t4][2030][11211][4.11.77] 在对连接的底层 socket、socket input stream 或 socket output stream 执行操作期间
发生通信错误。错误位置：Reply.fill() - socketInputStream.read (-1)。消息：Connection reset。 ERRORCODE=-4499, SQLSTATE=08001
	at com.ibm.db2.jcc.am.gd.a(gd.java:319)
	at com.ibm.db2.jcc.t4.a.a(a.java:461)
	at com.ibm.db2.jcc.t4.a.a(a.java:456)
	at com.ibm.db2.jcc.t4.z.b(z.java:206)
	at com.ibm.db2.jcc.t4.z.c(z.java:259)
	at com.ibm.db2.jcc.t4.z.c(z.java:372)
	at com.ibm.db2.jcc.t4.z.v(z.java:1147)
	at com.ibm.db2.jcc.t4.cb.f(cb.java:103)
	at com.ibm.db2.jcc.t4.q.f(q.java:87)
	at com.ibm.db2.jcc.t4.b.a(b.java:3642)
	at com.ibm.db2.jcc.am.cg.b(cg.java:41)
	at com.ibm.db2.jcc.am.hg.b(hg.java:196)
	at com.ibm.db2.jcc.am.o.j(o.java:579)
	at com.ibm.db2.jcc.am.o.g(o.java:325)
	at com.ibm.db2.jcc.t4.a.g(a.java:626)
	at com.ibm.db2.jcc.am.o.a(o.java:206)
	at com.ibm.db2.jcc.am.kn.b(kn.java:3799)
	at com.ibm.db2.jcc.am.ln.fc(ln.java:152)
	at com.ibm.db2.jcc.am.lc.a(lc.java:7809)
	at com.ibm.db2.jcc.am.lc.a(lc.java:6315)
	at com.ibm.db2.jcc.am.lc.getTables(lc.java:6221)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:185)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:62)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:67)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:368)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:310)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:1999)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:547)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:196)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at com.ibm.db2.jcc.t4.z.b(z.java:199)
	... 24 more
2017-05-12 18:43:16 WARN [com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#3] [com.mchange.v2.c3p0.impl.DefaultConnectionTester:?] - SQL State '08001' of Exception which occurred during a Connection test (fallback DatabaseMetaData test) implies that the database is invalid, and the pool should refill itself with fresh Connections.
com.ibm.db2.jcc.am.DisconnectNonTransientConnectionException: [jcc][t4][2030][11211][4.11.77] 在对连接的底层 socket、socket input stream 或 socket output stream 执行操作期间
发生通信错误。错误位置：Reply.fill() - socketInputStream.read (-1)。消息：Connection reset。 ERRORCODE=-4499, SQLSTATE=08001
	at com.ibm.db2.jcc.am.gd.a(gd.java:319)
	at com.ibm.db2.jcc.t4.a.a(a.java:461)
	at com.ibm.db2.jcc.t4.a.a(a.java:456)
	at com.ibm.db2.jcc.t4.z.b(z.java:206)
	at com.ibm.db2.jcc.t4.z.c(z.java:259)
	at com.ibm.db2.jcc.t4.z.c(z.java:372)
	at com.ibm.db2.jcc.t4.z.v(z.java:1147)
	at com.ibm.db2.jcc.t4.cb.f(cb.java:103)
	at com.ibm.db2.jcc.t4.q.f(q.java:87)
	at com.ibm.db2.jcc.t4.b.a(b.java:3642)
	at com.ibm.db2.jcc.am.cg.b(cg.java:41)
	at com.ibm.db2.jcc.am.hg.b(hg.java:196)
	at com.ibm.db2.jcc.am.o.j(o.java:579)
	at com.ibm.db2.jcc.am.o.g(o.java:325)
	at com.ibm.db2.jcc.t4.a.g(a.java:626)
	at com.ibm.db2.jcc.am.o.a(o.java:206)
	at com.ibm.db2.jcc.am.kn.b(kn.java:3799)
	at com.ibm.db2.jcc.am.ln.fc(ln.java:152)
	at com.ibm.db2.jcc.am.lc.a(lc.java:7809)
	at com.ibm.db2.jcc.am.lc.a(lc.java:6315)
	at com.ibm.db2.jcc.am.lc.getTables(lc.java:6221)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:185)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:62)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:67)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:368)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:310)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:1999)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:547)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:196)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at com.ibm.db2.jcc.t4.z.b(z.java:199)
	... 24 more
2017-05-12 18:43:16 WARN [com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#1] [com.mchange.v2.c3p0.impl.DefaultConnectionTester:?] - SQL State '08001' of Exception which occurred during a Connection test (fallback DatabaseMetaData test) implies that the database is invalid, and the pool should refill itself with fresh Connections.
com.ibm.db2.jcc.am.DisconnectNonTransientConnectionException: [jcc][t4][2030][11211][4.11.77] 在对连接的底层 socket、socket input stream 或 socket output stream 执行操作期间
发生通信错误。错误位置：Reply.fill() - socketInputStream.read (-1)。消息：Connection reset。 ERRORCODE=-4499, SQLSTATE=08001
	at com.ibm.db2.jcc.am.gd.a(gd.java:319)
	at com.ibm.db2.jcc.t4.a.a(a.java:461)
	at com.ibm.db2.jcc.t4.a.a(a.java:456)
	at com.ibm.db2.jcc.t4.z.b(z.java:206)
	at com.ibm.db2.jcc.t4.z.c(z.java:259)
	at com.ibm.db2.jcc.t4.z.c(z.java:372)
	at com.ibm.db2.jcc.t4.z.v(z.java:1147)
	at com.ibm.db2.jcc.t4.cb.f(cb.java:103)
	at com.ibm.db2.jcc.t4.q.f(q.java:87)
	at com.ibm.db2.jcc.t4.b.a(b.java:3642)
	at com.ibm.db2.jcc.am.cg.b(cg.java:41)
	at com.ibm.db2.jcc.am.hg.b(hg.java:196)
	at com.ibm.db2.jcc.am.o.j(o.java:579)
	at com.ibm.db2.jcc.am.o.g(o.java:325)
	at com.ibm.db2.jcc.t4.a.g(a.java:626)
	at com.ibm.db2.jcc.am.o.a(o.java:206)
	at com.ibm.db2.jcc.am.kn.b(kn.java:3799)
	at com.ibm.db2.jcc.am.ln.fc(ln.java:152)
	at com.ibm.db2.jcc.am.lc.a(lc.java:7809)
	at com.ibm.db2.jcc.am.lc.a(lc.java:6315)
	at com.ibm.db2.jcc.am.lc.getTables(lc.java:6221)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:185)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:62)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:67)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:368)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:310)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:1999)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:547)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:196)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at com.ibm.db2.jcc.t4.z.b(z.java:199)
	... 24 more
2017-05-12 18:43:16 WARN [com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#4] [com.mchange.v2.c3p0.impl.DefaultConnectionTester:?] - SQL State '08001' of Exception which occurred during a Connection test (fallback DatabaseMetaData test) implies that the database is invalid, and the pool should refill itself with fresh Connections.
com.ibm.db2.jcc.am.DisconnectNonTransientConnectionException: [jcc][t4][2030][11211][4.11.77] 在对连接的底层 socket、socket input stream 或 socket output stream 执行操作期间
发生通信错误。错误位置：Reply.fill() - socketInputStream.read (-1)。消息：Connection reset。 ERRORCODE=-4499, SQLSTATE=08001
	at com.ibm.db2.jcc.am.gd.a(gd.java:319)
	at com.ibm.db2.jcc.t4.a.a(a.java:461)
	at com.ibm.db2.jcc.t4.a.a(a.java:456)
	at com.ibm.db2.jcc.t4.z.b(z.java:206)
	at com.ibm.db2.jcc.t4.z.c(z.java:259)
	at com.ibm.db2.jcc.t4.z.c(z.java:372)
	at com.ibm.db2.jcc.t4.z.v(z.java:1147)
	at com.ibm.db2.jcc.t4.cb.f(cb.java:103)
	at com.ibm.db2.jcc.t4.q.f(q.java:87)
	at com.ibm.db2.jcc.t4.b.a(b.java:3642)
	at com.ibm.db2.jcc.am.cg.b(cg.java:41)
	at com.ibm.db2.jcc.am.hg.b(hg.java:196)
	at com.ibm.db2.jcc.am.o.j(o.java:579)
	at com.ibm.db2.jcc.am.o.g(o.java:325)
	at com.ibm.db2.jcc.t4.a.g(a.java:626)
	at com.ibm.db2.jcc.am.o.a(o.java:206)
	at com.ibm.db2.jcc.am.kn.b(kn.java:3799)
	at com.ibm.db2.jcc.am.ln.fc(ln.java:152)
	at com.ibm.db2.jcc.am.lc.a(lc.java:7809)
	at com.ibm.db2.jcc.am.lc.a(lc.java:6315)
	at com.ibm.db2.jcc.am.lc.getTables(lc.java:6221)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:185)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:62)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:67)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:368)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:310)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:1999)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:547)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:196)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at com.ibm.db2.jcc.t4.z.b(z.java:199)
	... 24 more
2017-05-12 18:43:16 WARN [com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#1] [com.mchange.v2.c3p0.impl.DefaultConnectionTester:?] - SQL State '08001' of Exception which occurred during a Connection test (fallback DatabaseMetaData test) implies that the database is invalid, and the pool should refill itself with fresh Connections.
com.ibm.db2.jcc.am.DisconnectNonTransientConnectionException: [jcc][t4][2030][11211][4.11.77] 在对连接的底层 socket、socket input stream 或 socket output stream 执行操作期间
发生通信错误。错误位置：Reply.fill() - socketInputStream.read (-1)。消息：Connection reset。 ERRORCODE=-4499, SQLSTATE=08001
	at com.ibm.db2.jcc.am.gd.a(gd.java:319)
	at com.ibm.db2.jcc.t4.a.a(a.java:461)
	at com.ibm.db2.jcc.t4.a.a(a.java:456)
	at com.ibm.db2.jcc.t4.z.b(z.java:206)
	at com.ibm.db2.jcc.t4.z.c(z.java:259)
	at com.ibm.db2.jcc.t4.z.c(z.java:372)
	at com.ibm.db2.jcc.t4.z.v(z.java:1147)
	at com.ibm.db2.jcc.t4.cb.f(cb.java:103)
	at com.ibm.db2.jcc.t4.q.f(q.java:87)
	at com.ibm.db2.jcc.t4.b.a(b.java:3642)
	at com.ibm.db2.jcc.am.cg.b(cg.java:41)
	at com.ibm.db2.jcc.am.hg.b(hg.java:196)
	at com.ibm.db2.jcc.am.o.j(o.java:579)
	at com.ibm.db2.jcc.am.o.g(o.java:325)
	at com.ibm.db2.jcc.t4.a.g(a.java:626)
	at com.ibm.db2.jcc.am.o.a(o.java:206)
	at com.ibm.db2.jcc.am.kn.b(kn.java:3799)
	at com.ibm.db2.jcc.am.ln.fc(ln.java:152)
	at com.ibm.db2.jcc.am.lc.a(lc.java:7809)
	at com.ibm.db2.jcc.am.lc.a(lc.java:6315)
	at com.ibm.db2.jcc.am.lc.getTables(lc.java:6221)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:185)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:62)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:67)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:368)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:310)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:1999)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:547)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:196)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at com.ibm.db2.jcc.t4.z.b(z.java:199)
	... 24 more
2017-05-12 18:43:17 WARN [com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#2] [com.mchange.v2.resourcepool.BasicResourcePool:?] - com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@54f127ca -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (1). Last acquisition attempt exception: 
com.ibm.db2.jcc.am.DisconnectNonTransientConnectionException: [jcc][t4][2030][11211][4.11.77] 在对连接的底层 socket、socket input stream 或 socket output stream 执行操作期间
发生通信错误。错误位置：T4Agent.sendRequest() - flush (-1)。消息：Broken pipe。 ERRORCODE=-4499, SQLSTATE=08001
	at com.ibm.db2.jcc.am.gd.a(gd.java:319)
	at com.ibm.db2.jcc.t4.a.a(a.java:461)
	at com.ibm.db2.jcc.t4.a.a(a.java:456)
	at com.ibm.db2.jcc.t4.a.C(a.java:397)
	at com.ibm.db2.jcc.t4.a.r(a.java:354)
	at com.ibm.db2.jcc.am.o.i(o.java:220)
	at com.ibm.db2.jcc.t4.b.b(b.java:1112)
	at com.ibm.db2.jcc.t4.b.d(b.java:696)
	at com.ibm.db2.jcc.t4.b.c(b.java:682)
	at com.ibm.db2.jcc.t4.b.a(b.java:367)
	at com.ibm.db2.jcc.t4.b.<init>(b.java:307)
	at com.ibm.db2.jcc.DB2SimpleDataSource.getConnection(DB2SimpleDataSource.java:214)
	at com.ibm.db2.jcc.DB2Driver.connect(DB2Driver.java:460)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:134)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:182)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:171)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:137)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1014)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$800(BasicResourcePool.java:32)
	at com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask.run(BasicResourcePool.java:1810)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:547)
Caused by: java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
	at com.ibm.db2.jcc.t4.fb.b(fb.java:1685)
	at com.ibm.db2.jcc.t4.fb.a(fb.java:1633)
	at com.ibm.db2.jcc.t4.a.C(a.java:390)
	... 17 more
2017-05-12 18:43:17 WARN [com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#1] [com.mchange.v2.c3p0.impl.DefaultConnectionTester:?] - SQL State '08001' of Exception which occurred during a Connection test (fallback DatabaseMetaData test) implies that the database is invalid, and the pool should refill itself with fresh Connections.
com.ibm.db2.jcc.am.DisconnectNonTransientConnectionException: [jcc][t4][2030][11211][4.11.77] 在对连接的底层 socket、socket input stream 或 socket output stream 执行操作期间
发生通信错误。错误位置：T4Agent.sendRequest() - flush (-1)。消息：Broken pipe。 ERRORCODE=-4499, SQLSTATE=08001
	at com.ibm.db2.jcc.am.gd.a(gd.java:319)
	at com.ibm.db2.jcc.t4.a.a(a.java:461)
	at com.ibm.db2.jcc.t4.a.a(a.java:456)
	at com.ibm.db2.jcc.t4.a.C(a.java:397)
	at com.ibm.db2.jcc.t4.a.r(a.java:354)
	at com.ibm.db2.jcc.am.o.a(o.java:204)
	at com.ibm.db2.jcc.am.kn.b(kn.java:3799)
	at com.ibm.db2.jcc.am.ln.fc(ln.java:152)
	at com.ibm.db2.jcc.am.lc.a(lc.java:7809)
	at com.ibm.db2.jcc.am.lc.a(lc.java:6315)
	at com.ibm.db2.jcc.am.lc.getTables(lc.java:6221)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:185)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:62)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:67)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:368)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:310)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:1999)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:547)
Caused by: java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
	at com.ibm.db2.jcc.t4.fb.b(fb.java:1685)
	at com.ibm.db2.jcc.t4.fb.a(fb.java:1633)
	at com.ibm.db2.jcc.t4.a.C(a.java:390)
	... 14 more
2017-05-12 18:43:17 WARN [com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#2] [com.mchange.v2.c3p0.impl.DefaultConnectionTester:?] - SQL State '08001' of Exception which occurred during a Connection test (fallback DatabaseMetaData test) implies that the database is invalid, and the pool should refill itself with fresh Connections.
com.ibm.db2.jcc.am.DisconnectNonTransientConnectionException: [jcc][t4][2030][11211][4.11.77] 在对连接的底层 socket、socket input stream 或 socket output stream 执行操作期间
发生通信错误。错误位置：T4Agent.sendRequest() - flush (-1)。消息：Broken pipe。 ERRORCODE=-4499, SQLSTATE=08001
	at com.ibm.db2.jcc.am.gd.a(gd.java:319)
	at com.ibm.db2.jcc.t4.a.a(a.java:461)
	at com.ibm.db2.jcc.t4.a.a(a.java:456)
	at com.ibm.db2.jcc.t4.a.C(a.java:397)
	at com.ibm.db2.jcc.t4.a.r(a.java:354)
	at com.ibm.db2.jcc.am.o.a(o.java:204)
	at com.ibm.db2.jcc.am.kn.b(kn.java:3799)
	at com.ibm.db2.jcc.am.ln.fc(ln.java:152)
	at com.ibm.db2.jcc.am.lc.a(lc.java:7809)
	at com.ibm.db2.jcc.am.lc.a(lc.java:6315)
	at com.ibm.db2.jcc.am.lc.getTables(lc.java:6221)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:185)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:62)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:67)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:368)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:310)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:1999)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:547)
Caused by: java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
	at com.ibm.db2.jcc.t4.fb.b(fb.java:1685)
	at com.ibm.db2.jcc.t4.fb.a(fb.java:1633)
	at com.ibm.db2.jcc.t4.a.C(a.java:390)
	... 14 more
2017-05-12 18:43:17 WARN [com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#0] [com.mchange.v2.c3p0.impl.DefaultConnectionTester:?] - SQL State '08001' of Exception which occurred during a Connection test (fallback DatabaseMetaData test) implies that the database is invalid, and the pool should refill itself with fresh Connections.
com.ibm.db2.jcc.am.DisconnectNonTransientConnectionException: [jcc][t4][2030][11211][4.11.77] 在对连接的底层 socket、socket input stream 或 socket output stream 执行操作期间
发生通信错误。错误位置：T4Agent.sendRequest() - flush (-1)。消息：Broken pipe。 ERRORCODE=-4499, SQLSTATE=08001
	at com.ibm.db2.jcc.am.gd.a(gd.java:319)
	at com.ibm.db2.jcc.t4.a.a(a.java:461)
	at com.ibm.db2.jcc.t4.a.a(a.java:456)
	at com.ibm.db2.jcc.t4.a.C(a.java:397)
	at com.ibm.db2.jcc.t4.a.r(a.java:354)
	at com.ibm.db2.jcc.am.o.a(o.java:204)
	at com.ibm.db2.jcc.am.kn.b(kn.java:3799)
	at com.ibm.db2.jcc.am.ln.fc(ln.java:152)
	at com.ibm.db2.jcc.am.lc.a(lc.java:7809)
	at com.ibm.db2.jcc.am.lc.a(lc.java:6315)
	at com.ibm.db2.jcc.am.lc.getTables(lc.java:6221)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:185)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:62)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:67)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:368)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:310)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:1999)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:547)
Caused by: java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
	at com.ibm.db2.jcc.t4.fb.b(fb.java:1685)
	at com.ibm.db2.jcc.t4.fb.a(fb.java:1633)
	at com.ibm.db2.jcc.t4.a.C(a.java:390)
	... 14 more
2017-05-12 19:00:18 WARN [Thread-17] [com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool:?] - A ConnectionTest has failed, reporting that all previously acquired Connections are likely invalid. The pool will be reset.
2017-05-17 10:42:13 WARN [Thread-11] [com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool:?] - A ConnectionTest has failed, reporting that all previously acquired Connections are likely invalid. The pool will be reset.
2017-05-17 10:45:50 INFO [Curator-Framework-0-SendThread(registry.bass.3g:12181)] [org.apache.zookeeper.ClientCnxn:?] - Opening socket connection to server registry.bass.3g/172.17.102.5:12181. Will not attempt to authenticate using SASL (unknown error)
2017-05-17 10:45:50 INFO [Thread-17] [com.yeepay.g3.utils.common.datasource.MonitorDataSource:?] - [10]use connection in 604479548 miliseconds
	at java.lang.Thread.getStackTrace(Thread.java:1589)
	at com.yeepay.g3.utils.common.datasource.MonitorDataSource.releaseConnection(MonitorDataSource.java:290)
	at com.yeepay.g3.utils.common.datasource.MonitorConnection.close(MonitorConnection.java:141)
	at com.yeepay.g3.utils.common.datasource.MonitorConnection.invoke(MonitorConnection.java:103)
	at com.sun.proxy.$Proxy64.close(Unknown Source)
	at com.yeepay.utils.jdbc.dal.support.separate.DsStatusDetector.doDetect(DsStatusDetector.java:128)
	at com.yeepay.utils.jdbc.dal.support.separate.DsStatusDetector$1.run(DsStatusDetector.java:80)
	at java.lang.Thread.run(Thread.java:745)

2017-05-17 10:45:50 WARN [com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#2] [com.mchange.v2.c3p0.impl.DefaultConnectionTester:?] - SQL State '08001' of Exception which occurred during a Connection test (fallback DatabaseMetaData test) implies that the database is invalid, and the pool should refill itself with fresh Connections.
com.ibm.db2.jcc.am.DisconnectNonTransientConnectionException: [jcc][t4][2030][11211][4.11.77] 在对连接的底层 socket、socket input stream 或 socket output stream 执行操作期间
发生通信错误。错误位置：T4Agent.sendRequest() - flush (-1)。消息：Broken pipe。 ERRORCODE=-4499, SQLSTATE=08001
	at com.ibm.db2.jcc.am.gd.a(gd.java:319)
	at com.ibm.db2.jcc.t4.a.a(a.java:461)
	at com.ibm.db2.jcc.t4.a.a(a.java:456)
	at com.ibm.db2.jcc.t4.a.C(a.java:397)
	at com.ibm.db2.jcc.t4.a.r(a.java:354)
	at com.ibm.db2.jcc.am.o.a(o.java:204)
	at com.ibm.db2.jcc.am.kn.b(kn.java:3799)
	at com.ibm.db2.jcc.am.ln.fc(ln.java:152)
	at com.ibm.db2.jcc.am.lc.a(lc.java:7809)
	at com.ibm.db2.jcc.am.lc.a(lc.java:6315)
	at com.ibm.db2.jcc.am.lc.getTables(lc.java:6221)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:185)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:62)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:67)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:368)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:310)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:1999)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:547)
Caused by: java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
	at com.ibm.db2.jcc.t4.fb.b(fb.java:1685)
	at com.ibm.db2.jcc.t4.fb.a(fb.java:1633)
	at com.ibm.db2.jcc.t4.a.C(a.java:390)
	... 14 more
2017-05-17 10:45:50 WARN [com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#3] [com.mchange.v2.c3p0.impl.DefaultConnectionTester:?] - SQL State '08001' of Exception which occurred during a Connection test (fallback DatabaseMetaData test) implies that the database is invalid, and the pool should refill itself with fresh Connections.
com.ibm.db2.jcc.am.DisconnectNonTransientConnectionException: [jcc][t4][2030][11211][4.11.77] 在对连接的底层 socket、socket input stream 或 socket output stream 执行操作期间
发生通信错误。错误位置：T4Agent.sendRequest() - flush (-1)。消息：Broken pipe。 ERRORCODE=-4499, SQLSTATE=08001
	at com.ibm.db2.jcc.am.gd.a(gd.java:319)
	at com.ibm.db2.jcc.t4.a.a(a.java:461)
	at com.ibm.db2.jcc.t4.a.a(a.java:456)
	at com.ibm.db2.jcc.t4.a.C(a.java:397)
	at com.ibm.db2.jcc.t4.a.r(a.java:354)
	at com.ibm.db2.jcc.am.o.a(o.java:204)
	at com.ibm.db2.jcc.am.kn.b(kn.java:3799)
	at com.ibm.db2.jcc.am.ln.fc(ln.java:152)
	at com.ibm.db2.jcc.am.lc.a(lc.java:7809)
	at com.ibm.db2.jcc.am.lc.a(lc.java:6315)
	at com.ibm.db2.jcc.am.lc.getTables(lc.java:6221)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:185)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:62)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:67)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:368)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:310)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:1999)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:547)
Caused by: java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
	at com.ibm.db2.jcc.t4.fb.b(fb.java:1685)
	at com.ibm.db2.jcc.t4.fb.a(fb.java:1633)
	at com.ibm.db2.jcc.t4.a.C(a.java:390)
	... 14 more
